Add a scene or page switcher in the lower right corner of the preview page on  issue #43
CloudOrc/SolidUI pull request #78
Opened 2023-07-06 15:41 UTC by 15100399015

### What is the purpose of the change

Add a scene or page switcher in the lower right corner of the preview page

### Related issues/PRs

Related issues: #43 

### Brief change log
/solidui-web/src/pages/Designer/Preview/index.tsx
/solidui-web/src/pages/Designer/Preview/PreviewPopup.tsx
/solidui-web/src/pages/Designer/Preview/preview.tsx

### Checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [x] I have explained the need for this PR and the problem it solves
- [x] I have explained the changes or the new features added to this PR
- [x] I have added tests corresponding to this change
- [x] I have updated the documentation to reflect this change
- [x] I have verified that this change is backward compatible 
- [x] **If this is a code change**: I have written unit tests to fully verify the new behavior.

2023-07-06 16:16 UTC, nutsjian requested changes

2023-07-06 16:16 UTC, nutsjian commented on solidui-web/src/pages/Designer/Preview/index.tsx
> +	console.log(props);
Since we will use ESLint to check the code, it's better to remove the console.log here

2023-07-06 16:16 UTC, nutsjian commented on solidui-web/src/pages/Designer/Preview/index.tsx
> +	console.log(scenePageOptions);
Since we will use ESLint to check the code, it's better to remove the console.log here

2023-07-06 16:16 UTC, nutsjian commented on solidui-web/src/pages/Designer/Preview/index.tsx
> +import _, { isNil } from "lodash-es";
It's better to use `import { isNil } from "lodash-es"`, when build the project, it can reduce the bundle size.

2023-07-06 16:27 UTC, nutsjian commented on solidui-web/src/pages/Designer/Preview/index.tsx
> +import _, { isNil } from "lodash-es";
use `isNil(xxx) instead of _.isNil(xxx)`

2023-07-07 01:04 UTC, 15100399015 commented on solidui-web/src/pages/Designer/Preview/index.tsx
> +	console.log(props);
ok

2023-07-07 01:05 UTC, 15100399015 commented on solidui-web/src/pages/Designer/Preview/index.tsx
> +	console.log(scenePageOptions);
ok

2023-07-07 01:05 UTC, 15100399015 commented on solidui-web/src/pages/Designer/Preview/index.tsx
> +import _, { isNil } from "lodash-es";
ok

2023-07-07 01:08 UTC, 15100399015 commented
I have solved the above problem

2023-07-07 04:05 UTC, merged